name: mahila_mitra
description: "Final Prototype of Mahila Mitra - App dedicated to Women Safety"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_svg: ^2.2.1
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.3.2
  twilio_flutter: ^0.9.0
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
